
/*

                                    ,▄█▄                 
    ]█▄▄                         ╓█████▌                 
    ▐██████▄                   ▄█████▓╣█                 
     ║████████▄,  ,  ,,▄,▄▄▄▓██████╬╬╣╣▌                 
      ╚███╣██████████▓▓▓▓██████████╩╠╬▓                  
       ╙█╬╬╬▓███████████████████████▒▓▌                  
        ╙▓█▓██████████████████████████                   
         ╚██████▀███████████╩█▓▌▐▓████▄                  
         '║█████`╣█Γ║████████▄▄φ▓█████▌                 
          ║█████████████████████▓█████▌                  
           █████████████▓▓████████████                   
           ║█████████████████████████                    
          ]█████████████████████████                     
         ,▓██████████████████████████                    
        ▓█████████████████████████████µ                  
       ▐███████████████████████████████▄▄                
       ║█████████████████████████████████╬╬╣▓            
   ,╔╦║███████████████████████████████████▓╬╬╣           
,≥≥⌠░░░╠▓████████████████████████████████████▓▓          
,;=-',▄█████████████████████████████████████████▓        
                                                         
                                                         
                                                         
  ██████╗ ███████╗██╗   ██╗ ██████╗██╗  ██╗██╗ ██████╗   
  ██╔══██╗██╔════╝╚██╗ ██╔╝██╔════╝██║  ██║██║██╔════╝   
  ██████╔╝███████╗ ╚████╔╝ ██║     ███████║██║██║        
  ██╔═══╝ ╚════██║  ╚██╔╝  ██║     ██╔══██║██║██║        
  ██║     ███████║   ██║   ╚██████╗██║  ██║██║╚██████╗   
  ╚═╝     ╚══════╝   ╚═╝    ╚═════╝╚═╝  ╚═╝╚═╝ ╚═════╝   
                                                         
                                                         

This file was automatically generated by my cat, Aster.
He does not want you mucking about with his files,
and we are pretty lax on trimming his nails.

I mean, we have him pretty well fenced in but he is an
escape artist and he still manages to get fleas!

My point is, don't go mucking about with his files!

He actually has a hopefully well-tempered message for
us humans, he says:

"
  Dear pathetic humans,

  Here is a haiku to keep you in line

  don't dare go mucking
  with my files, I lyke them fine
  prettierignore
"

*/
import { type CalendarDate, type DateTime } from '@rvoh/dream'
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BathOrShowerStylesEnum = "bath" | "bath_and_shower" | "none" | "shower";
export const BathOrShowerStylesEnumValues = [
  "bath",
  "bath_and_shower",
  "none",
  "shower"
] as const


export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type PlaceStylesEnum = "cabin" | "cave" | "cottage" | "dump" | "lean_to" | "tent" | "treehouse";
export const PlaceStylesEnumValues = [
  "cabin",
  "cave",
  "cottage",
  "dump",
  "lean_to",
  "tent",
  "treehouse"
] as const


export type RoomTypesEnum = "Bathroom" | "Bedroom" | "Den" | "Kitchen" | "LivingRoom";
export const RoomTypesEnumValues = [
  "Bathroom",
  "Bedroom",
  "Den",
  "Kitchen",
  "LivingRoom"
] as const

export type Timestamp = ColumnType<DateTime | CalendarDate>

export interface Guests {
  createdAt: Timestamp;
  id: Generated<string>;
  updatedAt: Timestamp;
  userId: string;
}

export interface HostPlaces {
  createdAt: Timestamp;
  deletedAt: Timestamp | null;
  hostId: string;
  id: Generated<string>;
  placeId: string;
  updatedAt: Timestamp;
}

export interface Hosts {
  createdAt: Timestamp;
  id: Generated<string>;
  updatedAt: Timestamp;
  userId: string;
}

export interface Places {
  createdAt: Timestamp;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  name: string;
  sleeps: number;
  style: PlaceStylesEnum;
  updatedAt: Timestamp;
}

export interface Rooms {
  bathOrShowerStyle: BathOrShowerStylesEnum | null;
  createdAt: Timestamp;
  deletedAt: Timestamp | null;
  id: Generated<string>;
  placeId: string;
  position: number | null;
  type: RoomTypesEnum;
  updatedAt: Timestamp;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  id: Generated<string>;
  updatedAt: Timestamp;
}

export interface DB {
  guests: Guests;
  host_places: HostPlaces;
  hosts: Hosts;
  places: Places;
  rooms: Rooms;
  users: Users;
}


export class DBClass {
  guests: Guests
  host_places: HostPlaces
  hosts: Hosts
  places: Places
  rooms: Rooms
  users: Users
}
