export const globalTypeConfig = {
  serializers: [
      'GuestSerializer',
      'GuestSummarySerializer',
      'HostSerializer',
      'HostSummarySerializer',
      'LocalizedTextSerializer',
      'LocalizedTextSummarySerializer',
      'PlaceForGuestsSerializer',
      'PlaceSerializer',
      'PlaceSummaryForGuestsSerializer',
      'PlaceSummarySerializer',
      'Room/ApplianceSerializer',
      'Room/BathOrShowerStyleSerializer',
      'Room/BathroomForGuestsSerializer',
      'Room/BathroomSerializer',
      'Room/BathroomSummarySerializer',
      'Room/BedTypeSerializer',
      'Room/BedroomForGuestsSerializer',
      'Room/BedroomSerializer',
      'Room/BedroomSummarySerializer',
      'Room/DenForGuestsSerializer',
      'Room/DenSerializer',
      'Room/DenSummarySerializer',
      'Room/KitchenForGuestsSerializer',
      'Room/KitchenSerializer',
      'Room/KitchenSummarySerializer',
      'Room/LivingRoomForGuestsSerializer',
      'Room/LivingRoomSerializer',
      'Room/LivingRoomSummarySerializer',
      'RoomForGuestsSerializer',
      'RoomSerializer',
      'RoomSummarySerializer'
    ],
} as const
