import { CalendarDate } from '@rvohealth/dream'
import { DateTime } from 'luxon'
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type PlaceStylesEnum = "cabin" | "cave" | "cottage" | "dump" | "lean_to" | "tent" | "treehouse";
export const PlaceStylesEnumValues = [
  "cabin",
  "cave",
  "cottage",
  "dump",
  "lean_to",
  "tent",
  "treehouse"
] as const

export type IdType = string | number | bigint
export type Timestamp = ColumnType<DateTime | CalendarDate>

export interface Guests {
  createdAt: Timestamp;
  id: Generated<Int8>;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface HostPlaces {
  createdAt: Timestamp;
  deletedAt: Timestamp | null;
  hostId: Int8;
  id: Generated<Int8>;
  placeId: Int8;
  updatedAt: Timestamp;
}

export interface Hosts {
  createdAt: Timestamp;
  id: Generated<Int8>;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface Places {
  createdAt: Timestamp;
  deletedAt: Timestamp | null;
  id: Generated<Int8>;
  name: string;
  style: PlaceStylesEnum;
  updatedAt: Timestamp;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  firstName: string;
  id: Generated<Int8>;
  lastName: string;
  updatedAt: Timestamp;
}

export interface DB {
  guests: Guests;
  host_places: HostPlaces;
  hosts: Hosts;
  places: Places;
  users: Users;
}


export class DBClass {
  guests: Guests
  host_places: HostPlaces
  hosts: Hosts
  places: Places
  users: Users
}
