import { CalendarDate } from '@rvohealth/dream'
import { DateTime } from 'luxon'
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;
export type IdType = string | number | bigint
export type Timestamp = ColumnType<DateTime | CalendarDate>

export interface Guests {
  createdAt: Timestamp;
  id: Generated<Int8>;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface Hosts {
  createdAt: Timestamp;
  id: Generated<Int8>;
  updatedAt: Timestamp;
  userId: Int8;
}

export interface Users {
  createdAt: Timestamp;
  email: string;
  firstName: string | null;
  id: Generated<Int8>;
  lastName: string | null;
  updatedAt: Timestamp;
}

export interface DB {
  guests: Guests;
  hosts: Hosts;
  users: Users;
}


export class DBClass {
  guests: Guests
  hosts: Hosts
  users: Users
}
